---
title: "git_01"
author: "Daniel Jones"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
  Some say in ice.  
  From what I've tasted of desire  
  I hold with those who favor fire.  
  But if it had to perish twice,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Do not go gentle into that good night,  
Old age should burn and rave at close of day;  
Rage, rage against the dying of the light.  
Though wise men at their end know dark is right,  
Because their words had forked no lightning they  
Do not go gentle into that good night.  
